# Generated by Django 2.0.1 on 2023-10-25 08:26
# モジュールをimport
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        # 既存のテーブルに新しいフィールドを追加
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
